# Generated by Django 5.0.9 on 2026-07-20 19:11

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(help_text='The filename as provided by the uploading client, before sanitization.', max_length=255)),
                ('stored_filename', models.CharField(help_text='The sanitized, collision-resistant filename used on disk.', max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=apps.documents.models.document_upload_path)),
                ('extension', models.CharField(max_length=16)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes.')),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Populated by the future Parser module. Null until parsed.', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('stored', 'Stored'), ('ready_for_parsing', 'Ready for Parsing'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('chunking', 'Chunking'), ('chunked', 'Chunked'), ('embedding', 'Generating Embeddings'), ('embedded', 'Embedded'), ('indexing_vector_db', 'Updating ChromaDB'), ('vector_indexed', 'Vector Indexed'), ('indexing_knowledge_graph', 'Updating Knowledge Graph'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('processing_stage', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('stored', 'Stored'), ('ready_for_parsing', 'Ready for Parsing'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('chunking', 'Chunking'), ('chunked', 'Chunked'), ('embedding', 'Generating Embeddings'), ('embedded', 'Embedded'), ('indexing_vector_db', 'Updating ChromaDB'), ('vector_indexed', 'Vector Indexed'), ('indexing_knowledge_graph', 'Updating Knowledge Graph'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='uploaded', help_text="Mirrors `status` for non-failed documents; retains the last active stage when `status` is FAILED so the UI can show 'Failed while Parsing', etc.", max_length=32)),
                ('processing_percentage', models.PositiveSmallIntegerField(default=0, help_text='Overall pipeline completion, 0-100.')),
                ('chunk_count', models.PositiveIntegerField(default=0, help_text='Populated by the future Chunker module.')),
                ('embedding_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Populated by the future Embedding Generator module.', max_length=16)),
                ('knowledge_graph_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Populated by the future Knowledge Graph module.', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='documents_d_status_07369e_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='documents_d_uploade_2fe388_idx')],
            },
        ),
    ]
