# Generated by Django 5.0.9 on 2026-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parser_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured metadata returned by the Parser module (title, author, dates, language, parser used, OCR used, timing, table/image counts, warnings). Empty until parsed.'),
        ),
    ]
