# Generated by Django 5.0.9 on 2026-07-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_parser_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunker_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured metadata returned by the Chunker module (total/text/table chunk counts, timing, warnings). Empty until chunked.'),
        ),
        migrations.AddField(
            model_name='document',
            name='chunking_time_seconds',
            field=models.FloatField(blank=True, help_text='Time taken by the Chunker module to process this document. Null until chunked.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0, help_text='Populated by the Chunker module once chunking completes.'),
        ),
    ]
