# Generated by Django 5.0.9 on 2026-07-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_embedding_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Populated by the Embedding Generator module (Sprint 7).', max_length=16),
        ),
    ]
