# Generated by Django 5.0.9 on 2026-07-21 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', help_text='Auto-generated or user-edited title.', max_length=255)),
                ('summary', models.TextField(blank=True, default='', help_text='AI-generated summary of the conversation.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('pinned', models.BooleanField(default=False)),
                ('equipment_mentioned', models.JSONField(blank=True, default=list)),
                ('documents_used', models.JSONField(blank=True, default=list)),
                ('knowledge_graph_nodes', models.JSONField(blank=True, default=list)),
                ('drawing_references', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField(help_text='The message text (question or answer).')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('retrieved_chunks', models.JSONField(blank=True, default=list)),
                ('knowledge_graph_refs', models.JSONField(blank=True, default=list)),
                ('drawing_refs', models.JSONField(blank=True, default=list)),
                ('related_equipment', models.JSONField(blank=True, default=list)),
                ('related_documents', models.JSONField(blank=True, default=list)),
                ('suggested_followups', models.JSONField(blank=True, default=list)),
                ('token_usage', models.PositiveIntegerField(default=0)),
                ('response_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='chat_conver_user_id_e2a76b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'status'], name='chat_conver_user_id_f98e31_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'pinned', '-updated_at'], name='chat_conver_user_id_3c2f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
    ]
